### ISSUE TITLE
Use `.zarr` instead of `.zarr.zip` for images and boundaries

### ISSUE THREAD

**Issue by jwrth** [SpatialPathology/InSituPy#105]
To load data from `zarr.zip` using `zarr.ZipStore`, data needs to be loaded into memory with `.persist()` because otherwise it cannot be accessed after the `ZipStore` is closed. This works fine for smaller data but for bigger data I realized that one runs into memory issues. Since it is not really possible to dynamically open and close the `ZipStore` in a safe way (always needs to run `.close()` which might not happen if the napari viewer crashes e.g.), switching to `.zarr` is probably the best way.

## TODOs

- [x] Implement saving of `.zarr` using `zarr.DirectoryStore()`
- [x] Set saving as `.zarr` as default for boundaries and images.
- [x] Test it on demo data and pancreas data

### Performance of different modes

![Image](https://github.com/SpatialPathology/InSituPy/assets/76480183/698b67e9-8f34-4cb2-abb9-d7e3a8d9e5d2)
