### ISSUE TITLE
Revise napari widgets

### ISSUE THREAD

**Issue by jwrth** [SpatialPathology/InSituPy#126]
## TODOs

- [x] Revise terminology of Add/show in widget: Add should be if something new gets added and show if data is displayed. Or maybe rather "Display data"?
- [x] Revise sizing of widgets
- [x] Group Show annotation and show regions into a tab
