### ISSUE TITLE
Allow alternative segmentations

### ISSUE THREAD

**Issue by jwrth** [SpatialPathology/InSituPy#25]
## Background

It would be good to include results from different segmentation algorithms (e.g. Baysor) or different parameter settings of the same algorithm.

## TODOs

- [x] #44 
- [x] Adapt cropping function
- [x] Adapt rest of code
- [x] Implement Baysor reader: #8 
- [x] Implement `layers` within `xd.cells` to save the alternative segmentations. Done in 01e50501a0a4896dabaa79a48ccbc3ba9be15c85
- [x] Implement visualization of alternative segmentations in napari - see #59 
- [ ] Add demo notebooks - see #109 
- [ ] Implement reading of alternative Xeniumranger outputs

## Ideas how to implement it

For alternative cell segmentations, the most important thing to read is the matrix. But also the `boundaries` change!!

- Introduce an `AnnDataCollection` class. Two options how to implement it:
  1. A separate class which has Anndata objects as arguments similar to `AnnotationData` or `ImageData`
  2. A child class to AnnData, inheriting all functionalities as AnnData with the addition of a key `.alts` for alternative matrices. One of the matrices can be set as main and is displayed then when calling `xd.matrix`.
  3. Introduce AnnDataCollection as additional layer in XeniumData (e.g. `alt_matrix`).
    - Advantages: 
      - This would keep the current syntax with `xd.matrix`
      - Makes it easy to set the "main" matrix by transferring it to the position `xd.matrix`
    - Disadvantages: 
      - would be more intuitive to have it as a sublevel of `xd.matrix`
- Always pair `matrix` and `boundaries` in a object called `cells`:
  - The syntax would be then `xd.cells.matrix` for calling the cells. And `xd.cells.boundaries` for calling the boundaries
  - For the nuclei/cells we could do `xd.cells.boundaries.nuclear` and `xd.cells.boundaries.cellular`

## Include boundaries into `anndata` in `xd.matrix`

see #33 -> was closed because it is probably too complicated to include shapely objects into the anndata object
Instead: see #44
