### ISSUE TITLE
Rename `XeniumData`

### ISSUE THREAD

**Issue by jwrth** [SpatialPathology/InSituPy#95]
## Background

Since the structure of the `XeniumData` object is not bound to the Xenium technology, renaming would make sense.

## Ideas for renaming
- `InSituData`
- `ISData`
- `insituData`

## TODOs for generalization

- [x] Rename the class to `InSituData` - 1597caabf37832575bdb0ee51d2cbdf0b4785a40
- [x] The data object would need following inputs:
  - Paths to all the modalities (which will then be used by `read_XXX`
  - Metadata such as pixel size
- [x] implementation of a `read_xenium` function in `InSituPy` - see 1597caabf37832575bdb0ee51d2cbdf0b4785a40
- [ ] general configuration file that is used by the `read_{technology}` function and easily adaptable. Could be YAML/TOML or JSON. [Here](https://martin-ueding.de/posts/json-vs-yaml-vs-toml/) is an opinion on the formats. For me YAML seems the most easy to read.
